services:
  web:
    build:
      context: .

    ports:
      - "3000:3000"

    restart: always

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DATABASE_URL=postgresql://inframitra:strongpassword@db:5432/hardware_marketplace

  postgres:
    image: postgres:16-alpine

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: hardware_marketplace

    ports:
      - "5432:5432"

    volumes:
      - app_pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  app_pgdata:
